version : '3.8'

volumes:
  redis:

services:

  backend:
    container_name: backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./backend/:/app/
      - ./docker/bash/:/app/bash/
      - ./backend/static/:/app/static/
      - /tmp/app/mysqld:/run/mysqld
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
    command: "run_django"

  redis:
    container_name: redis
    hostname: redis
    image: redis:5.0
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always

  celery:
    container_name: celery
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./backend/:/app/
      - ./docker/bash/:/app/bash/
    restart: always
    command: run_celery
    depends_on:
      redis:
        condition: service_started
