# Generated by Django 3.2.15 on 2023-08-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Артикул товара')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название товара')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
